baseurl = "https://filippo82.github.io/website_new_hugo/"
title = "Filippo B"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

publishDir = "../docs"

paginate = 20
canonifyurls = false

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    author = "Filippo B"
    info = "Rocket ship builder"
    description = "Filippo B's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/filippo_square.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    since = 2019

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

    enableTwemoji = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/filippo82/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/filippobroggini/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/olgias/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About me"
    weight = 100
    url = "/about/"
